//
// BuoyToggleView.h
// Generated by Core Animator version 1.3.1 on 7/23/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface BuoyToggleView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// Toggle Off
- (void)addToggleOffAnimation;
- (void)addToggleOffAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addToggleOffAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addToggleOffAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addToggleOffAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeToggleOffAnimation;

// Toggle On
- (void)addToggleOnAnimation;
- (void)addToggleOnAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addToggleOnAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addToggleOnAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addToggleOnAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeToggleOnAnimation;

- (void)removeAllAnimations;

@end