//
// OnSwitchView.h
// Generated by Core Animator version 1.3.1 on 4/25/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface OnSwitchView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// OFF
- (void)addOFFAnimation;
- (void)addOFFAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addOFFAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addOFFAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
//- (void)addOFFAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addOFFAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode withDuration:(CFTimeInterval)duration andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeOFFAnimation;

// OFF_reversed
- (void)addOFFReversedAnimation;
- (void)addOFFReversedAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addOFFReversedAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addOFFReversedAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
//- (void)addOFFReversedAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addOFFReversedAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode withDuration:(CFTimeInterval)duration andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeOFFReversedAnimation;

- (void)removeAllAnimations;

@end