platform :ios, '8.0'
inhibit_all_warnings!

target 'g5Mindr' do
    source 'https://github.com/CocoaPods/Specs.git'
    
    pod 'Mapbox-iOS-SDK', '~> 3.3.0'
    pod 'GoogleMaps'
    pod 'Google/Analytics'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'AMWaveTransition'
    pod 'ReactiveCocoa', '~> 2.5'

end
