platform :ios, '7.0'
inhibit_all_warnings!

target 'g5Mindr' do
    source 'https://github.com/CocoaPods/Specs.git'
    
    pod 'Mapbox-iOS-SDK'
    pod 'GoogleMaps'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'Mantle'
    pod 'PBJHexagon'
    pod 'AMWaveTransition'
    pod 'ReactiveCocoa'

end
